name: React Build

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: https://github.com/codewithsharu/templates/blob/main/.github/workflows/react-build.yml
    with:
      node-version: '18'
      build-folder: 'build'
      artifact-name: 'react-build'
