name: React Build

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: codewithsharu/templates/.github/workflows/react-build.yml@main
    with:
      node-version: '24.14.1'
      build-folder: dist
      artifact-name: react-build